# Generated by Django 4.2.7 on 2026-07-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreturn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturn',
            name='return_no',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
