# Generated by Django 4.2.7 on 2026-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
