# Generated by Django 4.2.7 on 2026-07-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('particular', models.CharField(choices=[('Sale', 'Sale'), ('Payment', 'Payment'), ('Sale Return', 'Sale Return'), ('Opening', 'Opening')], max_length=30)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=30)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='customers.customer')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
